### ISSUE TITLE
parking regulations

### ISSUE THREAD

**Issue by carstoid** [NYCPlanning/ud-digital-practice#70]
placeholder

**Comment by crystaljeksi** [comment]
sit down with zoning for specifics

**Comment by crystaljeksi** [comment]
Take a look at how the numbers are feeding into the model:
- Use Metro North as a Case to edit Excel sheet
- Identify if there is a standard parking requirement, not based on use for the zoning districts
- Identify what issues may come up if there is a use outside the standard number for the zoning district, and document how the user would make these adjustments or assign use with attached parking requirements into the tools capabilities
