### ISSUE TITLE
draft project overview 1-pager to Howard

### ISSUE THREAD

**Issue by carstoid** [NYCPlanning/ud-digital-practice#84]
for meeting prep, see #47 and #75 

- structured around identified areas of work/projects
  - maintaining a central 3d **model**/database (inter-divisional & interagency data coordination)
  - develop & provide support for model-driven **analysis** tools (service provision to other divisions)
  - develop model-driven **visualization** techniques and workflows (enhanced capacity within UD division, service provision to the public)
- UD to also coordinate resources and training to users/stakeholders
- [ ] needs discussion: how/whether to present open-source question

**Comment by carstoid** [comment]
feedback from erick/claudia 2/3
  - highlight how 3d model thing is foundational or about platform building
  - highlight that RWCDS tool is one part of analysis tools
  - Show examples for visualization
  - also indicate that we're doing this partly as a listening/user research phase

**Comment by crystaljeksi** [comment]
checking at 2/7 with updated brief
file in location: G:\Commons\Digital Practice Initiative\Admin\Memos

**Comment by carstoid** [comment]
last edit is in a new datestamped copy, same location. submitted 2/10
